version: "3"

services:
  etherd:
    build:
      context: .
    image: etherd
    container_name: etherd
    expose:
      - "8545"
    ports:
      - 8545:8545
    command: node index.js
    volumes:
      - etherd-data-volume:/etherd/db
      - etherd-data-volume:/etherd/keystore
      - ./config/geth.js:/etherd/config/geth.js
      - ./config/server.js:/etherd/config/server.js
      - ./config/tokens.js:/etherd/config/tokens.js

volumes:
  etherd-data-volume:
    external: true