version: "3"

services:
  etherd:
    build:
      context: .
    image: etherd
    hostname: etherd
    expose:
      - "8545"
    ports:
      - 8545:8545
    volumes:
      - etherd-data-volume:/root/etherd/keystore
    command: node index.js

volumes:
  etherd-data-volume:
    external: true